### ISSUE TITLE
Skymoth is running slowly

### ISSUE THREAD

**Issue by Bout2GitIt** [thilobillerbeck/skymoth#17]
**Describe the bug**
Skymoth takes 16 hours to post from Mastodon to Bluesky

**Expected behavior**
Previously, posts from Mastodon were cross-posted to Bluesky within minutes. It was great! But yesterday I noticed that my Mastodon post didn't make it over to Bluesky for 16 hours.

My most recent post on Mastodon (30 minutes ago) has not populated on Bluesky, either.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Phanpy running in WebCatalog

**Comment by querkmachine** [comment]
I noticed this issue and it now appears to have stopped cross posting completely. 

Going onto the website and trying to reconnect to Bluesky now returns an "Could not authenticate to Bluesky" error message.

I guess something has broken or been cut off?

**Comment by thilobillerbeck** [comment]
Hi, I am aware of this issue and just had not time yet to investigate, but I#ll try to do this evening. Sorry for the inconveniences, I hope I can fix this soon. Thanks for reporting and for using this project. <3

**Comment by thilobillerbeck** [comment]
seems to be an issue with rate limiting at first glance

**Comment by thilobillerbeck** [comment]
So there seems to be an issue with how the code currently handles Bluesky Sessions and how this does not seem to be a preferred method anymore. Trying to fix this asap.

**Comment by querkmachine** [comment]
@thilobillerbeck Thanks for looking into it!

**Comment by thilobillerbeck** [comment]
well maybe a TODO would be to somehow let the user decide what happens with clogged up content. Well... at least now it is on the other side :joy: 

sorry for everyone now having their posts ported over all at once :see_no_evil:

**Comment by thilobillerbeck** [comment]
seems to be resolved by now. I set the polling interval to 360s just to be sure things calm down nicely, will shorten this over the next days until I can assure stable operation again.

**Comment by thilobillerbeck** [comment]
I guess this is resolved by now. Feel free to reopen this should it occur again. :)

**Comment by Jerome-Herbinet** [comment]
Hi,

The 360s interval is not working by my side. 
I boosted some toots almost one hour ago, but they still don't appear on my Bluesky page.
